### ISSUE TITLE
Report 1

### ISSUE THREAD

**Issue by DavidSRoy** [DavidSRoy/sociable#1]
Test

**Comment by 0xMango** [comment]
(Frontend/UI)
Goals for the week:
- Design essential screens (signup/login, main chat interface, messaging/DMs, user feed, my profile/statuses, etc.)
- Design supplemental screens (creating chats, uploading content, mutual contacts, user profiles)
Next week:
- Continue supplemental screen designs
- Begin to implement essential screens

**Comment by sulaiman-cse-uw** [comment]
(fullstack) - Abas & Sulaiman

Goals for the week: 
- Help on designing the login and sign up screens. 
- Help the backend crew with programming portions 
-
Next Week: 
- continue screen design 
- continue writing , editing, and testing code
