### ISSUE TITLE
Unable to Clone Repo on XCode

### ISSUE THREAD

**Issue by evaliu2002** [DavidSRoy/sociable#53]
I am not sure if this is an issue with my device specifically, but after cloning the repo on XCode, I was unable to open the project. 
![image](https://user-images.githubusercontent.com/69877857/169769435-674e0e46-9ca3-46af-b995-55268ae4515b.png)

To Reproduce
1. Open XCode
2. Click "Clone an existing project"
3. Once the project is cloned, the project does not open. Instead the same window as when XCode first starts appears.
4. I click "Open a project or file" and try to open my cloned repo.
5. The bug (refer to above image) appears.

Expected behavior
I expect the repo to start up after cloning or I am able to open the repo folder from my local storage.

Desktop (please complete the following information):
OS: Macbook 13in Intel Monterey 12.3.1 (21E258)
Application: XCode
Version 13.4 (13F17a)

Additional context
I tried searching online for the solution to no avail.

**Comment by DavidSRoy** [comment]
Hi @evaliu2002,
Could you try cloning the repo via Terminal? Let me know if this resolves the issue

**Comment by evaliu2002** [comment]
Hi David. I did try cloning in the terminal and that didn't solve it unfortunately. Thanks for the advice

**Comment by 0xMango** [comment]
Sorry, we should of specified that after cloning you want to open the `iOS/` folder within the repo folder

**Comment by evaliu2002** [comment]
That solved it for me. Thank you!
