### ISSUE TITLE
Messaging Screen Displays Duplicate Messages and Incorrect Order, Does not 'send'

### ISSUE THREAD

**Issue by DavidSRoy** [DavidSRoy/sociable#57]
Repro Steps:
- Create account
[Messaging Screen opens]
- Enter text into the input
- Tap the Send icon (arrow)

**Comment by sanchezbrian** [comment]
i am having this issue as well. not sure what is supposed to happen after i hit send

**Comment by sulaiman-cse-uw** [comment]
Thanks, we'll look into this
